// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/edge/account": {
            "get": {
                "description": "取得帳戶資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "帳戶列表"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.EdgeAuth"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accountrouter.errMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "編輯帳戶列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "帳戶列表"
                ],
                "parameters": [
                    {
                        "description": "帳戶列表資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accountrouter.editAccountData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/accountrouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accountrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/browse": {
            "get": {
                "description": "取得所有Browse name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "設備列表"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/checkconverter": {
            "post": {
                "description": "檢查轉換表是否被編輯",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "設備列表"
                ],
                "parameters": [
                    {
                        "description": "轉換表資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/devicerouter.edConvInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/connect": {
            "get": {
                "description": "取得連線資訊\u003cbr\u003e status(value=0:異常,1:連線,2:斷線)\u003cbr\u003e Protocol(value=0:OPC UA,1:HTTP)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "連線列表"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.ConInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connectrouter.errMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "編輯連線資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "連線列表"
                ],
                "parameters": [
                    {
                        "description": "編輯資料",
                        "name": "editinfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connectrouter.updateCon"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connectrouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connectrouter.errMsg"
                        }
                    }
                }
            },
            "post": {
                "description": "新增連線資訊\u003cbr\u003e Protocol(value=0:OPC UA,1:HTTP)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "連線列表"
                ],
                "parameters": [
                    {
                        "description": "連線資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.ConInfo"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connectrouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connectrouter.errMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "刪除連線資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "連線列表"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "連線ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "連線名稱",
                        "name": "name",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/connectrouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connectrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/connectrecord": {
            "get": {
                "description": "取得系統記錄(type=0:異常,1:登入,2:登出)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系統記錄"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.ConnectRecord"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connectrecordrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/converter": {
            "get": {
                "description": "取得轉換表資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "設備列表"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.Converter"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "編輯資料轉換表資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "設備列表"
                ],
                "parameters": [
                    {
                        "description": "資料轉換表資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/devicerouter.edConvInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    }
                }
            },
            "post": {
                "description": "複製轉換表為新範本(data需提供轉換表所有欄位資料，name填入新範本名稱)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "設備列表"
                ],
                "parameters": [
                    {
                        "description": "轉換表所有欄位資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/devicerouter.edConvInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/device": {
            "get": {
                "description": "取得設備資訊\u003cbr\u003e Protocol(value=0:OPC UA,1:HTTP) \u003cbr\u003e若protocol=0 status(value=0:異常,1:運轉,2:閒置,3:Unknown) \u003cbr\u003e若protocol=1 status(value=2:停機,3:閒置,4:異常,5:運轉,7:不良品,其他數字:Unknown)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "設備列表"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.DevInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "編輯設備資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "設備列表"
                ],
                "parameters": [
                    {
                        "description": "設備編輯資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/devicerouter.devInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "刪除設備資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "設備列表"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/history": {
            "get": {
                "description": "取得所有歷史資料\u003cbr\u003e 若protocol=\"OPC UA\" Machine_Status(value=1:全自動,2:半自動,3:手動,4:設置,其他數字:Unknown) \u003cbr\u003e Machine_Motor(value=1:ON,0:OFF)\u003cbr\u003e 若protocol=\"HTTP\" Machine_Status(value=2:停機,3:閒置,4:異常,5:運轉,7:不良品,其他數字:Unknown)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歷史資料"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "選擇時間",
                        "name": "selectTime",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "顯示欄位",
                        "name": "columns",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/historyrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/importtemplate": {
            "post": {
                "description": "匯入範本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "範本列表"
                ],
                "parameters": [
                    {
                        "description": "範本關聯表資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templaterouter.editTmpRel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level0history": {
            "get": {
                "description": "取得level0歷史資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歷史資料"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "選擇時間",
                        "name": "selectTime",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/historyrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level0info": {
            "get": {
                "description": "取得設備 level 0 資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "即時看板"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/kanbanrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level1history": {
            "get": {
                "description": "取得level1歷史資料\u003cbr\u003e 若protocol=\"OPC UA\" Machine_Status(value=1:全自動,2:半自動,3:手動,4:設置,其他數字:Unknown) \u003cbr\u003e Machine_Motor(value=1:ON,0:OFF)\u003cbr\u003e 若protocol=\"HTTP\" Machine_Status(value=2:停機,3:閒置,4:異常,5:運轉,7:不良品,其他數字:Unknown)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歷史資料"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "選擇時間",
                        "name": "selectTime",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/historyrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level1info": {
            "get": {
                "description": "取得level1即時資料\u003cbr\u003e 若protocol=\"OPC UA\" Machine_Status(value=0：手動、1：半自動、2：全自動(電眼)、3：全自動(操作狀態Operation mode)) \u003cbr\u003e Machine_Motor(value=1:ON,0:OFF)\u003cbr\u003e 若protocol=\"HTTP\" Machine_Status(value=2:停機,3:閒置,4:異常,5:運轉,7:不良品,其他數字:Unknown)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "即時看板"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/kanbanrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level2history": {
            "get": {
                "description": "取得level2歷史資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歷史資料"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "選擇時間",
                        "name": "selectTime",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/historyrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level2info": {
            "get": {
                "description": "取得設備 level 2 資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "即時看板"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/kanbanrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level3history": {
            "get": {
                "description": "取得level3歷史資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歷史資料"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "選擇時間",
                        "name": "selectTime",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/historyrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level3info": {
            "get": {
                "description": "取得設備 level 3 資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "即時看板"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/kanbanrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level4history": {
            "get": {
                "description": "取得level4歷史資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歷史資料"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "選擇時間",
                        "name": "selectTime",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/historyrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/level4info": {
            "get": {
                "description": "取得設備 level 4 資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "即時看板"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "設備ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/edgeservice.NodeStruct"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/kanbanrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/login": {
            "get": {
                "description": "登入用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登入、登出功能"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "帳號",
                        "name": "account",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密碼(SHA512格式)",
                        "name": "password",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/loginrouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/loginrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/logout": {
            "get": {
                "description": "登出用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登入、登出功能"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "帳戶",
                        "name": "account",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/loginrouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/loginrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/model": {
            "get": {
                "description": "取得設備模型資料",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "範本列表"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/permission": {
            "get": {
                "description": "取得帳戶權限 \u003cbr\u003e action(value=0:None,1:Read,2:Write)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "帳戶列表"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "帳戶ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.AuthPermissopn"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accountrouter.errMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "編輯帳戶權限 \u003cbr\u003e action(value=0:None,1:Read,2:Write)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "帳戶列表"
                ],
                "parameters": [
                    {
                        "description": "帳戶權限資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accountrouter.editPermissionInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/accountrouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accountrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/scanip": {
            "get": {
                "description": "取得所有連線",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "連線列表"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ip範圍或單一IP",
                        "name": "ip",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.ConInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/connectrouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/template": {
            "get": {
                "description": "取得範本列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "範本列表"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.Template"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "編輯範本列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "範本列表"
                ],
                "parameters": [
                    {
                        "description": "編輯資料",
                        "name": "editinfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templaterouter.updateTemp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    }
                }
            },
            "post": {
                "description": "新增範本列表 \u003cbr\u003e使用複製範本功能，id填入來源範本id，name填入新範本名稱",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "範本列表"
                ],
                "parameters": [
                    {
                        "description": "範本資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templaterouter.tmpInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "刪除範本列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "範本列表"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "範本名稱",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/temprel": {
            "get": {
                "description": "取得範本關聯資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "範本列表"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "範本ID",
                        "name": "id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeattr.TemplateRel"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "編輯範本關聯資訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "範本列表"
                ],
                "parameters": [
                    {
                        "description": "範本關聯表資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templaterouter.editTmpRel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/templaterouter.errMsg"
                        }
                    }
                }
            }
        },
        "/edge/value": {
            "get": {
                "description": "取得欄位實際值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "設備列表"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "欄位NodeId",
                        "name": "nodeId",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "欄位namespace",
                        "name": "namespace",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "欄位browseName",
                        "name": "browseName",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "設備ID",
                        "name": "devId",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/devicerouter.errMsg"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "accountrouter.editAccountData": {
            "type": "object",
            "properties": {
                "editContent": {
                    "$ref": "#/definitions/nodeattr.EdgeAuth"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "accountrouter.editPermissionInfo": {
            "type": "object",
            "properties": {
                "editContent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nodeattr.AuthPermissopn"
                    }
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "accountrouter.errMsg": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "connectrecordrouter.errMsg": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "connectrouter.errMsg": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "connectrouter.updateCon": {
            "type": "object",
            "properties": {
                "editContent": {
                    "$ref": "#/definitions/nodeattr.ConInfo"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "devicerouter.devInfo": {
            "type": "object",
            "properties": {
                "editContent": {
                    "$ref": "#/definitions/nodeattr.DevInfo"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "devicerouter.edConvInfo": {
            "type": "object",
            "properties": {
                "editContent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nodeattr.Converter"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "devicerouter.errMsg": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "edgeservice.NodeStruct": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "object"
                }
            }
        },
        "historyrouter.errMsg": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "kanbanrouter.errMsg": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "loginrouter.errMsg": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "nodeattr.AuthPermissopn": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "integer"
                },
                "action": {
                    "type": "integer"
                },
                "browseName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "nodeattr.ConInfo": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "certification": {
                    "type": "string"
                },
                "exist": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "protocol": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "nodeattr.ConnectRecord": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "nodeattr.Converter": {
            "type": "object",
            "properties": {
                "convertFunc": {
                    "type": "string"
                },
                "dstBrowseName": {
                    "type": "string"
                },
                "dstNodeId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "modify": {
                    "type": "integer"
                },
                "referenceBrowseName1": {
                    "type": "string"
                },
                "referenceBrowseName2": {
                    "type": "string"
                },
                "referenceBrowseName3": {
                    "type": "string"
                },
                "srcBrowseName": {
                    "type": "string"
                },
                "srcDevName": {
                    "type": "string"
                },
                "srcNamespace": {
                    "type": "integer"
                },
                "srcNodeId": {
                    "type": "string"
                },
                "srcUnit": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "nodeattr.DevInfo": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "conId": {
                    "type": "integer"
                },
                "conName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "protocol": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "tempID": {
                    "type": "integer"
                },
                "tempName": {
                    "type": "string"
                }
            }
        },
        "nodeattr.EdgeAuth": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "nodeattr.Template": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "modifyTime": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "nodeattr.TemplateRel": {
            "type": "object",
            "properties": {
                "convertFunc": {
                    "type": "string"
                },
                "dstBrowseName": {
                    "type": "string"
                },
                "dstNodeId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "referenceBrowseName1": {
                    "type": "string"
                },
                "referenceBrowseName2": {
                    "type": "string"
                },
                "referenceBrowseName3": {
                    "type": "string"
                },
                "srcBrowseName": {
                    "type": "string"
                },
                "srcNamespace": {
                    "type": "integer"
                },
                "srcNodeId": {
                    "type": "string"
                },
                "srcUnit": {
                    "type": "string"
                },
                "templateId": {
                    "type": "integer"
                }
            }
        },
        "templaterouter.editTmpRel": {
            "type": "object",
            "properties": {
                "editContent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nodeattr.TemplateRel"
                    }
                },
                "name": {
                    "type": "string"
                },
                "templateId": {
                    "type": "integer"
                }
            }
        },
        "templaterouter.errMsg": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "templaterouter.tmpInfo": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "modifyTime": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "templaterouter.updateTemp": {
            "type": "object",
            "properties": {
                "editContent": {
                    "$ref": "#/definitions/nodeattr.Template"
                },
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
